
apply plugin: 'com.android.application'

android {
    namespace "com.asnap.app"
    compileSdk 34
    defaultConfig {
        applicationId "com.asnap.app"
        minSdk 22
        targetSdk 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnit4"
        aaptOptions {
             ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories {
    flatDir{
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
    implementation 'androidx.core:core-splashscreen:1.0.1'
}

// Ensure capacitor runtime is included
try {
    def capacitorProjectDir = file('../node_modules/@capacitor/android/capacitor')
    if (capacitorProjectDir.exists()) {
        implementation project(':capacitor-android')
    }
} catch(Exception e) {
    // Falls back if local project isn't found
}
